Receiving notification from android. Sending Notification to Android needs to be finished. Problem of: AttributeError: 'PolymorphicQuerySet' object has no attribute 'get_pk_val'